"""PostgreSQL behind the same small interface the services use with sqlite3 (`con.execute(sql, args)`, rows by name or
position, `lastrowid`, `rowcount`, `commit`), so one body of SQL serves both databases.

The services write SQLite-flavoured SQL with `?` placeholders and CamelCase names (`tbl_Assets.AssetCode`). Before a
statement reaches PostgreSQL, `translate` rewrites it:
  - every name with a capital letter is double-quoted, so PostgreSQL keeps its case (`A."AssetCode"`) and rows come
    back with the same keys as from SQLite; SQL keywords (written in capitals) are left alone;
  - `?` becomes `%s` and a literal `%` becomes `%%` (psycopg placeholders); `LIKE` becomes `ILIKE` (SQLite's LIKE
    ignores case); `INSERT OR IGNORE` becomes `INSERT ... ON CONFLICT DO NOTHING`;
  - DDL types: `INTEGER PRIMARY KEY AUTOINCREMENT` -> identity column, `REAL` -> `DOUBLE PRECISION`.
An INSERT into a table with an identity key returns the new key (`RETURNING`), which becomes `cursor.lastrowid`.
Translations are cached: each distinct statement is rewritten once.
"""
from __future__ import annotations

import re
from decimal import Decimal
from functools import lru_cache

import psycopg

Error = psycopg.Error
IntegrityError = psycopg.IntegrityError

# words written in capitals in our SQL that are SQL, not names (anything else with a capital letter is a name)
KEYWORDS = set("""
SELECT FROM WHERE AND OR NOT NULL IS IN AS ON JOIN LEFT RIGHT INNER OUTER CROSS FULL GROUP BY ORDER HAVING LIMIT OFFSET
DISTINCT CASE WHEN THEN ELSE END INSERT INTO VALUES UPDATE SET DELETE CREATE TABLE INDEX UNIQUE IF EXISTS PRIMARY KEY
REFERENCES DEFAULT INTEGER TEXT REAL UNION ALL ASC DESC BETWEEN LIKE ILIKE COALESCE SUM COUNT MIN MAX AVG ROUND CAST ABS
LOWER UPPER SUBSTR WITH RETURNING CONFLICT DO NOTHING TRUE FALSE ESCAPE CASCADE COLLATE NOCASE AUTOINCREMENT GENERATED
IDENTITY DOUBLE PRECISION ALTER ADD COLUMN NULLS FIRST LAST OR IGNORE REPLACE FOREIGN CONSTRAINT CHECK BIGINT NUMERIC
VARCHAR BOOLEAN DATE TIMESTAMP INTERVAL EXCEPT INTERSECT USING
""".split())

_TOKEN = re.compile(r"""('(?:[^']|'')*')|("(?:[^"]|"")*")|([A-Za-z_][A-Za-z0-9_]*)|(\?)|(%)|(\s+)|(.)""", re.S)


def _quote_names(sql: str, params: bool) -> str:
    out = []
    for lit, quoted, word, qmark, pct, space, other in _TOKEN.findall(sql):
        if lit:
            out.append(lit.replace("%", "%%") if params else lit)
        elif quoted:
            out.append(quoted)
        elif word:
            if word.upper() == "LIKE":
                out.append("ILIKE")
            elif any(c.isupper() for c in word) and word not in KEYWORDS:
                out.append(f'"{word}"')
            else:
                out.append(word)
        elif qmark:
            out.append("%s")
        elif pct:
            out.append("%%" if params else "%")
        else:
            out.append(space or other)
    return "".join(out)


def _ddl(sql: str) -> str:
    sql = re.sub(r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql, flags=re.I)
    sql = re.sub(r"\bREAL\b", "DOUBLE PRECISION", sql)
    return re.sub(r"\s+COLLATE\s+NOCASE", "", sql, flags=re.I)


@lru_cache(maxsize=4096)
def translate(sql: str, params: bool = True) -> str:
    s = sql.strip().rstrip(";")
    if re.match(r"(?is)^\s*(CREATE|ALTER)\b", s):
        s = _ddl(s)
    if re.match(r"(?is)^\s*INSERT\s+OR\s+IGNORE\s+INTO\b", s):
        s = re.sub(r"(?is)^\s*INSERT\s+OR\s+IGNORE\s+INTO\b", "INSERT INTO", s)
        parts = re.split(r"(?i)\b(?=RETURNING\b)", s, maxsplit=1)
        s = f"{parts[0].rstrip()} ON CONFLICT DO NOTHING" + (f" {parts[1]}" if len(parts) > 1 else "")
    return _quote_names(s, params)


class Row(tuple):
    """A result row read by position (`r[0]`) or by column name (`r["AssetCode"]`), like sqlite3.Row."""
    __slots__ = ()
    _names: tuple = ()
    _index: dict = {}

    def __getitem__(self, k):
        if isinstance(k, str):
            return tuple.__getitem__(self, self._index[k])
        return tuple.__getitem__(self, k)

    def keys(self):
        return list(self._names)


@lru_cache(maxsize=1024)
def _row_class(names: tuple) -> type:
    return type("Row", (Row,), {"__slots__": (), "_names": names, "_index": {n: i for i, n in enumerate(names)}})


def _value(v):
    return float(v) if isinstance(v, Decimal) else v


def _param(v):
    return int(v) if isinstance(v, bool) else v   # the columns hold 0/1 integers, as in SQLite


class Cursor:
    def __init__(self, cur, lastrowid=None):
        self._cur, self.lastrowid = cur, lastrowid
        self.rowcount = cur.rowcount
        names = tuple(d.name for d in cur.description) if cur.description else ()
        self._cls = _row_class(names) if names else None
        self._buffer: list | None = None

    def _wrap(self, raw):
        return self._cls(tuple(_value(v) for v in raw))

    def fetchone(self):
        if self._buffer is not None:
            return self._buffer.pop(0) if self._buffer else None
        if not self._cls:
            return None
        raw = self._cur.fetchone()
        return self._wrap(raw) if raw is not None else None

    def fetchall(self):
        if self._buffer is not None:
            out, self._buffer = self._buffer, []
            return out
        return [self._wrap(r) for r in self._cur.fetchall()] if self._cls else []

    def __iter__(self):
        return iter(self.fetchall())


class Connection:
    """The sqlite3.Connection subset the app uses, on a psycopg connection."""

    def __init__(self, url: str, pks: dict[str, str]):
        self._con = psycopg.connect(url, autocommit=False)
        self._pks = pks   # table -> identity key, for lastrowid
        self.row_factory = None

    def _returning(self, sql: str) -> tuple[str, str | None]:
        m = re.match(r"(?is)^\s*INSERT\s+(?:OR\s+IGNORE\s+)?INTO\s+(\w+)", sql)
        pk = self._pks.get(m.group(1)) if m else None
        if pk and not re.search(r"(?i)\bRETURNING\b", sql):
            return sql.strip().rstrip(";") + f" RETURNING {pk}", pk
        return sql, None

    def execute(self, sql: str, args=()):
        sql2, pk = self._returning(sql)
        cur = self._con.cursor()
        cur.execute(translate(sql2, True), tuple(_param(a) for a in (args or ())))
        if pk:
            rows = cur.fetchall()
            out = Cursor(cur, rows[-1][0] if rows else None)
            out._buffer = []
            return out
        return Cursor(cur)

    def executemany(self, sql: str, seq):
        cur = self._con.cursor()
        cur.executemany(translate(sql, True), [tuple(_param(a) for a in row) for row in seq])
        return Cursor(cur)

    def bulk_insert(self, table: str, cols: list[str], rows: list) -> None:
        """Many rows at once through COPY (tens of thousands of journal lines in a fraction of a second)."""
        with self._con.cursor().copy(f'COPY "{table}" ({", ".join(f'"{c}"' for c in cols)}) FROM STDIN') as cp:
            for r in rows:
                cp.write_row([_param(v) for v in r])

    def executescript(self, script: str):
        for stmt in split_script(script):
            self._con.execute(translate(stmt, False))

    def commit(self):
        self._con.commit()

    def rollback(self):
        self._con.rollback()

    def close(self):
        self._con.close()


def split_script(script: str) -> list[str]:
    """Statements of a script (our DDL has no semicolons inside strings)."""
    return [s.strip() for s in script.split(";") if s.strip()]


def columns(con: Connection, table: str) -> list[str]:
    return [r[0] for r in con._con.execute(
        "SELECT column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=%s", (table,)).fetchall()]


def reset_sequences(con: Connection, pks: dict[str, str]) -> None:
    """After rows were inserted with explicit keys (a migration or a restore), new keys continue after the highest one."""
    for table, pk in pks.items():
        con._con.execute(f"""SELECT setval(pg_get_serial_sequence('"{table}"', '{pk}'),
            COALESCE((SELECT MAX("{pk}") FROM "{table}"), 0) + 1, false)""")
