"""Builds web/src/ar.ts from the dictionary below (English UI string -> Arabic)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ar = {
    # shell / common
    "Fixed assets": "الأصول الثابتة", "Workspace": "مساحة العمل", "Workspaces": "مساحات العمل", "Common": "عام",
    "All fixed assets": "جميع الأصول الثابتة", "New fixed asset": "أصل ثابت جديد", "Periodic tasks": "المهام الدورية",
    "Depreciation run": "تشغيل الإهلاك", "Depreciation periods": "فترات الإهلاك", "Inquiries": "الاستعلامات",
    "Fixed asset journal": "يومية الأصول الثابتة", "Fixed asset transactions": "حركات الأصول الثابتة", "Audit log": "سجل التدقيق",
    "Reports": "التقارير", "Fixed asset reports": "تقارير الأصول الثابتة", "Setup": "الإعداد",
    "Fixed asset groups": "مجموعات الأصول الثابتة", "Depreciation methods": "طرق الإهلاك", "Locations": "المواقع",
    "Cost centers": "مراكز التكلفة", "Ledger accounts": "حسابات الأستاذ", "Fixed asset parameters": "معاملات الأصول الثابتة",
    "Language": "اللغة", "Navigation": "التنقل", "Go to asset…": "الانتقال إلى أصل…", "Search assets": "بحث في الأصول",
    "No matches": "لا توجد نتائج", "Loading…": "جارٍ التحميل…", "Search…": "بحث…", "Search": "بحث", "Close": "إغلاق",
    "Confirm": "تأكيد", "Yes": "نعم", "Cancel": "إلغاء", "OK": "موافق", "Save": "حفظ", "Saved": "تم الحفظ", "Saved {0}": "تم حفظ {0}",
    "New": "جديد", "Edit": "تعديل", "Delete": "حذف", "Deleted": "تم الحذف", "Refresh": "تحديث", "Back to list": "العودة للقائمة",
    "Export to Excel": "تصدير إلى Excel", "Show more": "عرض المزيد", "{0} records": "{0} سجل", "{0} lines": "{0} سطر",
    "{0} files": "{0} ملف", "Total": "الإجمالي", "Subtotal": "إجمالي فرعي",
    "Fill in the required fields.": "يرجى تعبئة الحقول المطلوبة.", "No records to show.": "لا توجد سجلات للعرض.",
    "Select an asset first.": "اختر أصلاً أولاً.", "Select a record first.": "اختر سجلاً أولاً.", "Select a period first.": "اختر فترة أولاً.",
    # dashboard
    "Active fixed assets": "الأصول الثابتة النشطة", "Acquisition cost": "تكلفة الاقتناء", "Accumulated depreciation": "مجمع الإهلاك",
    "Net book value": "صافي القيمة الدفترية", "No fixed assets yet.": "لا توجد أصول ثابتة بعد.",
    "Posted depreciation by period": "الإهلاك المرحّل حسب الفترة", "No depreciation has been posted yet.": "لم يتم ترحيل أي إهلاك بعد.",
    "Next period to depreciate": "الفترة التالية للإهلاك", "Unposted depreciation lines": "سطور إهلاك غير مرحّلة",
    "Current period": "الفترة الحالية", "No warranties expiring in the next 90 days.": "لا توجد ضمانات تنتهي خلال 90 يوماً.",
    "No transactions yet.": "لا توجد حركات بعد.", "Net book value by group": "صافي القيمة الدفترية حسب المجموعة",
    "Open register": "فتح السجل", "Depreciation posted by period": "الإهلاك المرحّل حسب الفترة", "Schedule": "الجدول",
    "To do": "المطلوب إنجازه", "Warranties expiring soon": "ضمانات قاربت على الانتهاء", "Recent transactions": "أحدث الحركات", "All": "الكل",
    # asset list
    "Asset": "الأصل", "Name": "الاسم", "Group": "المجموعة", "Status": "الحالة", "Acquired": "تاريخ الاقتناء", "Location": "الموقع",
    "Cost center": "مركز التكلفة", "Cost": "التكلفة", "Accum. depreciation": "مجمع الإهلاك", "All statuses": "جميع الحالات",
    "All groups": "جميع المجموعات", "No fixed assets match the filter.": "لا توجد أصول مطابقة.",
    # statuses / types
    "Active": "نشط", "Inactive": "غير نشط", "Under Repair": "تحت الصيانة", "Disposed": "مستبعد", "Draft": "مسودة", "DRAFT": "مسودة",
    "NEW": "جديد", "POSTED": "مرحّل", "Posted": "مرحّل", "OPEN": "مفتوحة", "CLOSED": "مغلقة", "ACQUISITION": "اقتناء",
    "DISPOSAL": "استبعاد", "TRANSFER": "تحويل", "STATUS": "تغيير حالة", "DEPRECIATION": "إهلاك", "Depreciation": "الإهلاك",
    "Disposal": "استبعاد", "reopened": "أُعيد فتحها", "closed": "أُغلقت",
    # asset form
    "Asset number": "رقم الأصل", "Fixed asset group": "مجموعة الأصل الثابت", "Description": "الوصف", "General": "عام",
    "Acquisition and cost": "الاقتناء والتكلفة", "Acquisition date": "تاريخ الاقتناء", "Residual (salvage) value": "القيمة التخريدية",
    "In-service date": "تاريخ بدء الاستخدام", "Depreciation start date": "تاريخ بدء الإهلاك",
    "Depreciation is proposed from the period containing this date.": "يُقترح الإهلاك ابتداءً من الفترة التي تحتوي هذا التاريخ.",
    "Opening accumulated depreciation": "مجمع الإهلاك الافتتاحي", "Only for assets brought in with prior depreciation.": "فقط للأصول المنقولة مع إهلاك سابق.",
    "Depreciation method": "طريقة الإهلاك", "Useful life (years)": "العمر الإنتاجي (سنوات)", "Annual rate (%)": "النسبة السنوية (%)",
    "Location and responsibility": "الموقع والمسؤولية", "Responsible person": "المسؤول عن الأصل", "Purchase and warranty": "الشراء والضمان",
    "Supplier": "المورد", "Invoice number": "رقم الفاتورة", "Purchase order": "أمر الشراء", "Warranty expiry": "انتهاء الضمان",
    "Identification": "التعريف", "Manufacturer": "الشركة المصنعة", "Model": "الموديل", "Serial number": "الرقم التسلسلي",
    "Notes": "ملاحظات", "years": "سنة",
    "Depreciation has been posted for this asset, so cost, life, method and dates are locked.": "تم ترحيل إهلاك لهذا الأصل، لذلك التكلفة والعمر والطريقة والتواريخ مقفلة.",
    "This asset was disposed on {0} and is read-only.": "تم استبعاد هذا الأصل بتاريخ {0} وهو للقراءة فقط.",
    "Depreciation history": "سجل الإهلاك", "Transactions": "الحركات", "Attachments": "المرفقات", "Book value": "القيمة الدفترية",
    "In service": "قيد الاستخدام", "Last depreciation": "آخر إهلاك", "Fixed asset": "أصل ثابت",
    "Transfer": "تحويل", "Change status": "تغيير الحالة", "Dispose": "استبعاد", "Asset deleted": "تم حذف الأصل",
    "Delete asset {0}? This cannot be undone.": "حذف الأصل {0}؟ لا يمكن التراجع.",
    "Period": "الفترة", "Opening accum. dep.": "مجمع الإهلاك الافتتاحي", "Closing accum. dep.": "مجمع الإهلاك الختامي",
    "No depreciation lines.": "لا توجد سطور إهلاك.", "No transactions.": "لا توجد حركات.",
    "Date": "التاريخ", "Type": "النوع", "Amount": "المبلغ", "From location": "من موقع", "To location": "إلى موقع",
    "Proceeds": "المتحصلات", "Reference": "المرجع", "User": "المستخدم", "Title": "العنوان", "File": "الملف", "Added": "أضيف",
    "Remove": "إزالة", "Remove this attachment?": "إزالة هذا المرفق؟", "Attachment removed": "تمت إزالة المرفق",
    "Attachment added": "تمت إضافة المرفق", "No attachments.": "لا توجد مرفقات.",
    "Drop files here or click to attach (PDF, images, Excel, CSV, any type)": "أفلت الملفات هنا أو انقر للإرفاق (PDF وصور وExcel وCSV وأي صيغة)", "Files are attached when you save.": "تُرفق الملفات عند الحفظ.", "{0} file(s) attached": "تم إرفاق {0} ملف", "{0} file(s) could not be attached": "تعذّر إرفاق {0} ملف", "Attach file": "إرفاق ملف", "Attach": "إرفاق",
    "Document type": "نوع المستند", "Invoice": "فاتورة", "Warranty": "ضمان", "Contract": "عقد", "Photo": "صورة", "Manual": "دليل", "Other": "أخرى",
    "Transfer asset {0}": "تحويل الأصل {0}", "Transfer date": "تاريخ التحويل", "To cost center": "إلى مركز التكلفة",
    "Current: {0} / {1}": "الحالي: {0} / {1}", "Asset transferred": "تم تحويل الأصل", "Asset transferred ": "تم تحويل الأصل",
    "New status": "الحالة الجديدة", "Status updated": "تم تحديث الحالة", "Disposal date": "تاريخ الاستبعاد",
    "Sale proceeds": "متحصلات البيع", "Reason": "السبب", "Dispose asset {0}": "استبعاد الأصل {0}", "Asset disposed": "تم استبعاد الأصل",
    "Net book value {0} · proceeds {1} · {2} {3}": "صافي القيمة الدفترية {0} · المتحصلات {1} · {2} {3}", "gain": "ربح", "loss": "خسارة",
    # depreciation pages
    "No depreciation periods exist yet.": "لا توجد فترات إهلاك بعد.", "Create periods": "إنشاء الفترات", "Create proposal": "إنشاء اقتراح",
    "Post": "ترحيل", "Discard proposal": "تجاهل الاقتراح", "Journal": "اليومية",
    "No eligible assets for this period.": "لا توجد أصول مؤهلة لهذه الفترة.", "Already posted": "مرحّل مسبقاً",
    "Not yet in depreciation": "لم يبدأ إهلاكه بعد", "Method: no depreciation": "الطريقة: بدون إهلاك", "Missing useful life": "العمر الإنتاجي مفقود",
    "Fully depreciated": "مهلك بالكامل", "Disposed ": "مستبعد",
    "{0} new · {1} draft · {2} posted. Create the proposal, review it, then post.": "{0} جديد · {1} مسودة · {2} مرحّل. أنشئ الاقتراح وراجعه ثم رحّله.",
    "This period is closed. Depreciation cannot be changed.": "هذه الفترة مغلقة ولا يمكن تعديل الإهلاك.",
    "{0} line(s) proposed": "تم اقتراح {0} سطر", "Post {0} depreciation line(s) for {1}, total {2}?": "ترحيل {0} سطر إهلاك للفترة {1} بإجمالي {2}؟",
    "Posted {0} line(s), total {1}": "تم ترحيل {0} سطر بإجمالي {1}", "Discard the unposted proposal?": "تجاهل الاقتراح غير المرحّل؟", "Discard": "تجاهل",
    "Generate fiscal year": "إنشاء سنة مالية", "Generate periods": "إنشاء الفترات", "Generate": "إنشاء", "Periods generated": "تم إنشاء الفترات",
    "Fiscal year": "السنة المالية", "Close period": "إغلاق الفترة", "Reopen period": "إعادة فتح الفترة", "Period {0}": "الفترة {0}",
    "Closing a period blocks any posting into it. Periods are created from the fiscal-year start month in the parameters.": "إغلاق الفترة يمنع أي ترحيل فيها. تُنشأ الفترات من شهر بداية السنة المالية في المعاملات.",
    "No.": "رقم", "Start": "البداية", "End": "النهاية", "All periods": "جميع الفترات", "All types": "جميع الأنواع",
    "Account": "الحساب", "Account name": "اسم الحساب", "Debit": "مدين", "Credit": "دائن", "Date / time": "التاريخ / الوقت",
    "Action": "الإجراء", "Entity": "الكيان", "Record": "السجل", "Details": "التفاصيل",
    # setup
    "Code": "الرمز", "Life (years)": "العمر (سنوات)", "Rate %": "النسبة %", "Left blank = 100 / life.": "إذا تُركت فارغة = 100 ÷ العمر.",
    "Fixed asset account": "حساب الأصل الثابت", "Accumulated depreciation account": "حساب مجمع الإهلاك",
    "Depreciation expense account": "حساب مصروف الإهلاك", "Gain on disposal account": "حساب أرباح الاستبعاد",
    "Loss on disposal account": "حساب خسائر الاستبعاد", "FIXED ASSET": "أصل ثابت", "ACCUMULATED DEPRECIATION": "مجمع إهلاك",
    "EXPENSE": "مصروف", "OTHER INCOME": "إيراد آخر", "OTHER EXPENSE": "مصروف آخر", "CLEARING": "حساب وسيط",
    "SL = straight line (the only method that calculates; any other code = no depreciation).": "SL = القسط الثابت (الطريقة الوحيدة المحتسبة؛ أي رمز آخر = بدون إهلاك).",
    "Delete this record?": "حذف هذا السجل؟", "Company name": "اسم الشركة", "Currency": "العملة", "Asset number prefix": "بادئة رقم الأصل",
    "New assets are numbered PREFIX-0001, PREFIX-0002…": "تُرقَّم الأصول الجديدة PREFIX-0001 وهكذا…",
    "Fiscal year start month": "شهر بداية السنة المالية", "Disposal proceeds (clearing) account": "حساب متحصلات الاستبعاد (وسيط)",
    "Attachments folder": "مجلد المرفقات", "Leave blank to use the 'attachments' folder next to the application.": "اتركه فارغاً لاستخدام مجلد attachments بجوار التطبيق.",
    "Dark mode": "الوضع الليلي",
    "Search for a page": "البحث عن صفحة", "All reports": "كل التقارير", "Net of VAT": "صافي دون الضريبة", "{0} groups": "{0} مجموعة", "{0}% of cost": "{0}% من التكلفة",
    "None overdue": "لا متأخر", "Assets in employee custody": "الأصول في عهدة الموظفين", "Not part of asset reports": "لا تدخل في تقارير الأصول",
    "Fixed assets ": "الأصول الثابتة", "Depreciation ": "الإهلاك", "Transactions ": "الحركات", "Exceptions": "استثناءات", "Maintenance ": "الصيانة", "Suppliers ": "الموردون", "Contacts ": "جهات الاتصال",
    "Contacts": "جهات الاتصال", "Employees": "الموظفون", "Employee": "الموظف", "New employee": "موظف جديد", "Asset custody": "عهد الأصول", "Custody": "العهدة", "Custody record": "سجل عهدة",
    "Employee code": "كود الموظف", "Employee name": "اسم الموظف", "Job title": "المسمى الوظيفي", "Department": "الإدارة / القسم", "ID number": "رقم الهوية", "Hire date": "تاريخ التعيين",
    "Assets held": "الأصول في العهدة", "Total custody": "إجمالي العهد", "Select an employee first.": "اختر موظفاً أولاً.", "No employees yet.": "لا يوجد موظفون بعد.",
    "Employee {0} created": "تم إنشاء الموظف {0}", "Delete employee {0}?": "حذف الموظف {0}؟", "Employee deleted": "تم حذف الموظف",
    "Issue asset": "تسليم أصل", "Issue to employee": "تسليم لموظف", "Issue asset to employee": "تسليم أصل لموظف", "Issue": "تسليم", "Issued": "مسلَّمة", "Returned": "مُعادة",
    "Issued by": "المُسلِّم", "Issue date": "تاريخ التسليم", "Condition on issue": "الحالة عند التسليم", "Accessories / included items": "الملحقات / المرفقات", "Good": "جيدة",
    "Custody {0} created": "تم إنشاء العهدة {0}", "Custody": "العهدة", "Return asset": "استرجاع الأصل", "Return asset {0}": "استرجاع الأصل {0}", "Return date": "تاريخ الإرجاع",
    "Condition on return": "الحالة عند الإرجاع", "Asset returned": "تم استرجاع الأصل", "Return details": "بيانات الإرجاع", "Return": "الإرجاع", "Handover details": "بيانات التسليم",
    "Employee and asset": "الموظف والأصل", "Signed form": "النموذج الموقّع", "Signed documents": "المستندات الموقّعة", "Attach signed form": "إرفاق النموذج الموقّع",
    "Attached": "مرفق", "Missing": "ناقص", "No signed documents yet.": "لا توجد مستندات موقّعة بعد.", "No custody records.": "لا توجد عهد.", "No custody records match the filter.": "لا توجد عهد مطابقة.",
    "Print handover form": "طباعة نموذج الاستلام", "Print return form": "طباعة نموذج الإرجاع", "Handover form": "نموذج الاستلام", "Return form": "نموذج الإرجاع", "Forms": "النماذج", "Form": "النموذج",
    "Back to custody": "العودة للعهدة", "Open": "فتح", "Select a custody record first.": "اختر سجل عهدة أولاً.", "Delete custody {0}?": "حذف العهدة {0}؟", "Custody deleted": "تم حذف العهدة",
    "Print the handover form, get it signed, then attach the signed copy here.": "اطبع نموذج الاستلام ووقّعه ثم أرفق النسخة الموقّعة هنا.", "Held by": "بحوزة", "All employees": "كل الموظفين",
    "Signature": "التوقيع", "Name": "الاسم", "Date": "التاريخ", "Custody status": "حالة العهدة", "Employee ": "الموظف",
    "Custody by employee": "العهد حسب الموظف", "Employees directory": "دليل الموظفين",
    "What each employee received: assets, dates, condition and whether they are still held.": "ما استلمه كل موظف: الأصول والتواريخ والحالة وهل ما زالت بحوزته.",
    "All employees with their contact details and the number of assets they hold.": "كل الموظفين مع بيانات الاتصال وعدد الأصول التي بحوزتهم.",
    "Serial number": "الرقم التسلسلي", "Condition on issue ": "الحالة عند التسليم", "Custody ": "العهدة", "Returned ": "أُعيدت", "Assets held ": "الأصول في العهدة",
    "Employee not found": "الموظف غير موجود", "Employee name is required": "اسم الموظف مطلوب", "Employee is required": "الموظف مطلوب", "This employee is inactive": "هذا الموظف غير نشط",
    "Employee code is too long": "كود الموظف طويل جداً", "Hire date is not valid": "تاريخ التعيين غير صالح",
    "This employee still holds assets; take them back before deactivating": "ما زال الموظف يحمل أصولاً؛ استرجعها قبل إيقافه",
    "This employee has custody records and cannot be deleted. Mark the employee inactive instead.": "لهذا الموظف سجلات عهدة ولا يمكن حذفه. عيّنه كغير نشط بدلاً من ذلك.",
    "Custody record not found": "سجل العهدة غير موجود", "A returned custody record cannot be edited": "لا يمكن تعديل عهدة مُعادة", "This asset was already returned": "تم استرجاع هذا الأصل مسبقاً",
    "Return date cannot be before the issue date": "تاريخ الإرجاع لا يسبق تاريخ التسليم", "Issue date cannot be before the acquisition date": "تاريخ التسليم لا يسبق تاريخ الاقتناء",
    "Only an issued custody record without signed documents can be deleted": "لا تُحذف إلا عهدة مسلَّمة بلا مستندات موقّعة",
    "Return the asset from the employee custody first": "استرجع الأصل من عهدة الموظف أولاً", "This asset has custody records and cannot be deleted": "لهذا الأصل سجلات عهدة ولا يمكن حذفه",
    "There are no open periods.": "لا توجد فترات مفتوحة.", "There are no closed periods.": "لا توجد فترات مغلقة.", "{0}: {1}": "{0}: {1}",
    "Choose the backup folder first (Settings > Backup > Location)": "حدّد مجلد النسخ الاحتياطي أولاً (الإعدادات ← النسخ الاحتياطي ← المكان)",
    "Supplier code": "كود المورد", "Location": "المكان", "Supplier code is too long": "كود المورد طويل جداً",
    "Open folder": "فتح المجلد", "Location and notes": "المكان والملاحظات", "Backup folder saved": "تم حفظ مجلد النسخ الاحتياطي", "Save folder": "حفظ المجلد",
    "This folder cannot be used (missing or not writable)": "لا يمكن استخدام هذا المجلد (غير موجود أو غير قابل للكتابة)",
    "Currencies": "العملات", "Currency": "العملة", "Symbol": "الرمز", "Default": "الافتراضية", "Set as default": "تعيين كافتراضية", "Default currency is now {0}": "العملة الافتراضية الآن {0}",
    "3-letter ISO 4217 code, e.g. SAR.": "رمز من 3 أحرف حسب معيار ISO 4217، مثل SAR.", "Choose a currency from the list": "اختر عملة من القائمة",
    "The default currency cannot be deleted": "لا يمكن حذف العملة الافتراضية", "The default currency cannot be made inactive": "لا يمكن إيقاف العملة الافتراضية",
    "Currency code must be 3 letters (ISO 4217)": "رمز العملة 3 أحرف (ISO 4217)",
    "Tax (VAT)": "الضريبة (القيمة المضافة)", "Track VAT on asset purchases": "تتبّع ضريبة القيمة المضافة على مشتريات الأصول", "Standard VAT rate (%)": "نسبة الضريبة الأساسية (%)",
    "Company VAT registration number": "الرقم الضريبي للشركة", "New assets are purchased with VAT": "الأصول الجديدة تُشترى بضريبة", "Invoice amounts include VAT": "مبالغ الفواتير شاملة الضريبة",
    "Default for the asset form; it can be changed per asset.": "قيمة افتراضية في نموذج الأصل ويمكن تغييرها لكل أصل.",
    "Fixed assets are always recorded and reported at their net cost, excluding VAT. VAT only marks whether an asset was purchased with VAT, so reports and depreciation are never affected by it.": "تُسجَّل الأصول الثابتة وتُعرض في التقارير دائماً بصافي التكلفة دون الضريبة. الضريبة تميّز فقط الأصول المشتراة بضريبة عن غيرها، فلا تتأثر بها التقارير ولا الإهلاك.",
    "Tax settings saved": "تم حفظ إعدادات الضريبة", "Yes": "نعم", "No": "لا", "Inclusive of VAT": "شامل الضريبة", "Exclusive of VAT": "غير شامل الضريبة",
    "Purchased with VAT": "مشترى بضريبة", "Invoice amount is": "مبلغ الفاتورة", "VAT rate (%)": "نسبة الضريبة (%)", "Invoice amount": "مبلغ الفاتورة",
    "VAT amount (not part of cost)": "مبلغ الضريبة (ليس جزءاً من التكلفة)", "Net cost (recorded in books)": "صافي التكلفة (المسجَّل في الدفاتر)",
    "Cost, depreciation and reports always use the net value, excluding VAT.": "التكلفة والإهلاك والتقارير تعتمد دائماً على الصافي دون الضريبة.",
    "VAT (not in cost)": "الضريبة (خارج التكلفة)", "VAT": "الضريبة", "With VAT": "بضريبة", "No VAT": "بدون ضريبة", "VAT status": "حالة الضريبة", "VAT amount": "مبلغ الضريبة",
    "Net cost": "صافي التكلفة", "Total with VAT": "الإجمالي مع الضريبة", "VAT rate": "نسبة الضريبة", "Invoice basis": "أساس الفاتورة", "Inclusive": "شامل", "Exclusive": "غير شامل",
    "VAT on asset purchases": "الضريبة على مشتريات الأصول", "Net cost, VAT amount and invoice basis of every purchase, to tell VAT and non-VAT assets apart.": "صافي التكلفة ومبلغ الضريبة وأساس الفاتورة لكل عملية شراء، لتمييز الأصول الخاضعة للضريبة وغيرها.",
    "VAT rate must be between 0 and 100": "نسبة الضريبة بين 0 و100", "Invoice amount must be a number": "مبلغ الفاتورة يجب أن يكون رقماً",
    "Automatic backup": "النسخ الاحتياطي التلقائي", "Frequency": "التكرار", "Off": "متوقف", "Daily": "يومي", "Weekly": "أسبوعي", "Monthly": "شهري", "Quarterly": "ربع سنوي",
    "Time": "الوقت", "Day of the week": "يوم الأسبوع", "Day of the month": "يوم الشهر", "Automatic backups to keep": "عدد النسخ التلقائية المحتفظ بها",
    "1-28. Quarterly backups run in January, April, July and October.": "من 1 إلى 28. تُؤخذ النسخ الربع سنوية في يناير وأبريل ويوليو وأكتوبر.",
    "Older automatic backups are deleted. 0 keeps all.": "تُحذف النسخ التلقائية الأقدم. 0 يعني الاحتفاظ بالكل.",
    "Automatic backup is off.": "النسخ الاحتياطي التلقائي متوقف.", "Next automatic backup": "النسخة التلقائية القادمة", "Last automatic backup": "آخر نسخة تلقائية",
    "Backup schedule saved": "تم حفظ جدول النسخ الاحتياطي", "Save schedule": "حفظ الجدول", "Schedule": "الجدول", "Automatic": "تلقائي", "Manual": "يدوي", "Backups": "النسخ الاحتياطية",
    "Automatic backups run while Gooya Asset is open. If the computer was off at the scheduled time, the backup is taken as soon as the app starts.": "تعمل النسخ التلقائية أثناء فتح Gooya Asset. إذا كان الجهاز مغلقاً وقت الجدولة تؤخذ النسخة فور تشغيل التطبيق.",
    "Monday": "الاثنين", "Tuesday": "الثلاثاء", "Wednesday": "الأربعاء", "Thursday": "الخميس", "Friday": "الجمعة", "Saturday": "السبت", "Sunday": "الأحد",
    "Invalid backup frequency": "تكرار النسخ غير صالح", "Backup time must be HH:MM": "وقت النسخ بصيغة HH:MM", "Invalid weekday": "يوم غير صالح",
    "Day of month must be 1-28": "يوم الشهر بين 1 و28", "Backups to keep must be 0-999": "عدد النسخ المحتفظ بها من 0 إلى 999",
    "Fixed asset": "أصل ثابت", "Manage": "إدارة", "View": "عرض", "Work order": "أمر العمل", "Printed by": "طُبع بواسطة", "Select row": "تحديد الصف",
    "Maintenance": "الصيانة", "Depreciation": "الإهلاك", "Suppliers": "الموردون",
    "Backup folder": "مجلد النسخ الاحتياطي",
    "Backup": "النسخ الاحتياطي", "Backup now": "نسخ احتياطي الآن", "Create backup now": "إنشاء نسخة احتياطية الآن", "Backup folder": "مجلد النسخ الاحتياطي",
    "Backup created: {0} ({1})": "تم إنشاء النسخة الاحتياطية: {0} ({1})", "No backups yet.": "لا توجد نسخ احتياطية بعد.", "Backups are saved in:": "تُحفظ النسخ الاحتياطية في:",
    "File": "الملف", "Created": "تاريخ الإنشاء", "Size": "الحجم", "Backup not found": "النسخة الاحتياطية غير موجودة",
    "A backup contains the database and all attachment files. To restore, stop the app and run the restore tool with the backup file:": "النسخة الاحتياطية تحوي قاعدة البيانات وكل ملفات المرفقات. للاستعادة أوقف التطبيق ثم شغّل أداة الاستعادة مع ملف النسخة:",
    "Leave blank to use the 'backups' folder next to the application. A cloud or network folder is recommended.": "اتركه فارغاً لاستخدام مجلد backups بجوار التطبيق. يُفضَّل مجلد سحابي أو شبكي.",
    "Suppliers": "الموردون", "Supplier": "المورد", "New supplier": "مورد جديد", "Supplier name": "اسم المورد", "No suppliers yet.": "لا يوجد موردون بعد.",
    "Select a supplier first.": "اختر مورداً أولاً.", "Supplier {0} created": "تم إنشاء المورد {0}", "Delete supplier {0}?": "حذف المورد {0}؟", "Supplier deleted": "تم حذف المورد",
    "Contact": "الاتصال", "Contact person": "الشخص المسؤول", "Phone": "الهاتف", "Mobile": "الجوال", "Email": "البريد الإلكتروني", "Website": "الموقع الإلكتروني",
    "Address": "العنوان", "City": "المدينة", "Country": "الدولة", "Saudi Arabia": "المملكة العربية السعودية", "Tax and banking": "الضريبة والبنك",
    "Tax (VAT) number": "الرقم الضريبي", "Tax number": "الرقم الضريبي", "Commercial registration": "السجل التجاري", "Payment terms": "شروط الدفع", "Bank": "البنك", "IBAN": "الآيبان",
    "Spaces are removed automatically.": "تُحذف المسافات تلقائياً.", "Activity": "النشاط", "Assets purchased": "الأصول المشتراة", "Purchases": "المشتريات",
    "Maintenance cost": "تكلفة الصيانة", "No assets purchased from this supplier.": "لا أصول مشتراة من هذا المورد.", "Supplier": "المورد",
    "Supplier": "المورد", "Manufacturer": "الشركة المصنعة", "Maintenance provider": "جهة صيانة", "Service provider": "مزود خدمة", "Supplier type": "نوع المورد",
    "Suppliers directory": "دليل الموردين", "Purchases by supplier": "المشتريات حسب المورد", "Supplier spend summary": "ملخص الإنفاق على الموردين",
    "All suppliers with their contact, tax and payment details.": "كل الموردين مع بيانات الاتصال والضريبة والدفع.",
    "Assets bought from each supplier with invoice and cost.": "الأصول المشتراة من كل مورد مع الفاتورة والتكلفة.",
    "Purchases and completed maintenance cost per supplier.": "المشتريات وتكلفة الصيانة المنفذة لكل مورد.",
    "Invoice": "فاتورة", "Total spend": "إجمالي الإنفاق", "Maintenance orders ": "أوامر الصيانة",
    "Supplier not found": "المورد غير موجود", "Supplier name is required": "اسم المورد مطلوب", "Invalid supplier type": "نوع مورد غير صالح",
    "Email address is not valid": "البريد الإلكتروني غير صالح",
    "This supplier is linked to assets or maintenance orders and cannot be deleted. Mark it inactive instead.": "هذا المورد مرتبط بأصول أو أوامر صيانة ولا يمكن حذفه. عيّنه كغير نشط بدلاً من ذلك.", "Assigned automatically from the fixed asset group.": "يُعطى تلقائياً حسب مجموعة الأصل الثابت.", "Nothing to depreciate in this period.": "لا يوجد إهلاك لهذه الفترة.", "Go to {0}": "انتقل إلى {0}",
    "Maintenance": "الصيانة", "Maintenance orders": "أوامر الصيانة", "Maintenance order": "أمر صيانة", "New maintenance order": "أمر صيانة جديد",
    "New maintenance": "صيانة جديدة", "Open maintenance orders": "أوامر الصيانة المفتوحة", "Open orders": "الأوامر المفتوحة", "{0} overdue": "{0} متأخر",
    "No open maintenance orders.": "لا توجد أوامر صيانة مفتوحة.", "Maintenance due": "صيانة مستحقة", "{0} orders": "{0} أمر",
    "No maintenance orders.": "لا توجد أوامر صيانة.", "No maintenance orders match the filter.": "لا توجد أوامر صيانة مطابقة.",
    "Completed maintenance cost: {0}": "تكلفة الصيانة المنفذة: {0}", "Order": "الأمر", "Order number": "رقم الأمر", "(assigned on save)": "(يُعطى عند الحفظ)",
    "Scheduled": "المجدول", "Scheduled date": "التاريخ المجدول", "Start date": "تاريخ البدء", "Completion date": "تاريخ الإنجاز", "Next due date": "تاريخ الاستحقاق القادم",
    "Priority": "الأولوية", "Low": "منخفضة", "Medium": "متوسطة", "High": "عالية", "Preventive": "وقائية", "Corrective": "علاجية", "Inspection": "فحص",
    "Planned": "مخطط", "In Progress": "قيد التنفيذ", "Completed": "مكتمل", "Cancelled": "ملغي", "Overdue": "متأخر", "Open": "مفتوح",
    "Vendor": "المورد / الجهة المنفذة", "Performed by": "نُفّذ بواسطة", "Cost and vendor": "التكلفة والجهة المنفذة", "Schedule ": "الجدولة", "Title": "العنوان",
    "Start work": "بدء العمل", "Complete": "إنجاز", "Cancel order": "إلغاء الأمر", "Complete {0}": "إنجاز {0}", "Cancel order {0}?": "إلغاء الأمر {0}؟",
    "Delete order {0}?": "حذف الأمر {0}؟", "Order deleted": "تم حذف الأمر", "Order cancelled": "تم إلغاء الأمر", "Work started": "بدأ العمل", "Maintenance completed": "تم إنجاز الصيانة",
    "Select an order first.": "اختر أمراً أولاً.", "Summary": "ملخص", "Asset is out of service during the work (status becomes Under Repair)": "الأصل خارج الخدمة أثناء العمل (تصبح حالته تحت الصيانة)",
    "Optional: schedules the next service for this asset.": "اختياري: يجدول الخدمة القادمة لهذا الأصل.", "For recurring maintenance; appears in the schedule report.": "للصيانة الدورية؛ يظهر في تقرير الجدولة.",
    "Maintenance cost is an expense; it does not change the asset cost.": "تكلفة الصيانة مصروف ولا تغيّر تكلفة الأصل.",
    "This order is overdue (scheduled {0}).": "هذا الأمر متأخر (مجدول بتاريخ {0}).", "This order is {0} and is read-only.": "هذا الأمر {0} وهو للقراءة فقط.",
    "Maintenance history": "سجل الصيانة", "Maintenance cost analysis": "تحليل تكلفة الصيانة", "Maintenance schedule and overdue": "جدول الصيانة والمتأخرات",
    "Every maintenance order per asset with vendor and cost.": "كل أوامر الصيانة لكل أصل مع الجهة المنفذة والتكلفة.",
    "Completed maintenance cost and count by asset, group or type.": "تكلفة وعدد الصيانة المنفذة حسب الأصل أو المجموعة أو النوع.",
    "Open orders and recurring due dates that are overdue or coming up.": "الأوامر المفتوحة وتواريخ الاستحقاق الدورية المتأخرة أو القادمة.",
    "Order status": "حالة الأمر", "Maintenance type": "نوع الصيانة", "Completed orders": "الأوامر المنفذة", "Total cost": "إجمالي التكلفة", "Average cost": "متوسط التكلفة",
    "Due date": "تاريخ الاستحقاق", "Days to due": "الأيام للاستحقاق", "Timing": "التوقيت", "Due": "مستحق", "Source": "المصدر", "Next due": "الاستحقاق القادم",
    "Open order": "أمر مفتوح", "Recurring due date": "استحقاق دوري", "Due within {0} days": "مستحق خلال {0} يوماً",
    "Complete or cancel the open maintenance orders of this asset first": "أنجز أو ألغِ أوامر الصيانة المفتوحة لهذا الأصل أولاً",
    "This asset has maintenance records and cannot be deleted": "لهذا الأصل سجلات صيانة ولا يمكن حذفه", "Maintenance order not found": "أمر الصيانة غير موجود",
    "A completed or cancelled order cannot be edited": "لا يمكن تعديل أمر مكتمل أو ملغي", "The asset cannot be changed once work has started": "لا يمكن تغيير الأصل بعد بدء العمل",
    "Only a planned order can be started": "يمكن بدء الأمر المخطط فقط", "Only an open order can be completed": "يمكن إنجاز الأمر المفتوح فقط", "Only an open order can be cancelled": "يمكن إلغاء الأمر المفتوح فقط",
    "Only a planned or cancelled order can be deleted": "يمكن حذف الأمر المخطط أو الملغي فقط", "Completion date cannot be before the start date": "تاريخ الإنجاز لا يسبق تاريخ البدء",
    "Next due date must be after the completion date": "تاريخ الاستحقاق القادم بعد تاريخ الإنجاز", "Asset is required": "الأصل مطلوب", "Title is required": "العنوان مطلوب",
    "Invalid maintenance type": "نوع صيانة غير صالح", "Invalid priority": "أولوية غير صالحة", "Unknown action": "إجراء غير معروف",
    "Name (Arabic)": "الاسم (بالعربية)", "Settings": "الإعدادات", "Settings sections": "أقسام الإعدادات",
    "Parameters saved": "تم حفظ المعاملات", "en-US": "ar",
    # reports
    "Fixed asset register": "سجل الأصول الثابتة", "Fixed asset summary": "ملخص الأصول الثابتة",
    "Fixed asset roll-forward": "حركة الأصول الثابتة (الرصيد المرحّل)", "Depreciation schedule": "جدول الإهلاك",
    "Fixed asset journal postings": "ترحيلات يومية الأصول", "Ledger account balances": "أرصدة حسابات الأستاذ",
    "Disposals and gain / loss": "الاستبعادات والأرباح / الخسائر", "Asset transactions": "حركات الأصول",
    "Fully depreciated assets": "الأصول المهلكة بالكامل", "Warranty expiry ": "انتهاء الضمان",
    "Cost, accumulated depreciation and net book value of every asset at a date.": "التكلفة ومجمع الإهلاك وصافي القيمة الدفترية لكل أصل في تاريخ معيّن.",
    "Totals by group, location or cost center at a date.": "الإجماليات حسب المجموعة أو الموقع أو مركز التكلفة في تاريخ معيّن.",
    "Opening balance, additions, disposals, depreciation and closing balance by group.": "الرصيد الافتتاحي والإضافات والاستبعادات والإهلاك والرصيد الختامي حسب المجموعة.",
    "Depreciation lines per asset and period for a fiscal year.": "سطور الإهلاك لكل أصل وفترة خلال سنة مالية.",
    "Posted debit and credit lines to the ledger accounts.": "سطور المدين والدائن المرحّلة إلى حسابات الأستاذ.",
    "Fixed asset postings summarised by ledger account.": "ترحيلات الأصول الثابتة ملخصة حسب حساب الأستاذ.",
    "Assets sold or scrapped, with net book value, proceeds and result.": "الأصول المباعة أو المخردة مع صافي القيمة والمتحصلات والنتيجة.",
    "Acquisitions, transfers, status changes and disposals.": "الاقتناءات والتحويلات وتغييرات الحالة والاستبعادات.",
    "Assets still in use whose net book value reached the residual value.": "أصول ما زالت مستخدمة وبلغ صافي قيمتها الدفترية القيمة التخريدية.",
    "Assets whose warranty has expired or is about to.": "أصول انتهى ضمانها أو قارب على الانتهاء.",
    "Exceptions": "استثناءات", "As of date": "كما في تاريخ", "From date": "من تاريخ", "To date": "إلى تاريخ", "Group by": "تجميع حسب",
    "Transaction type": "نوع الحركة", "Days ahead": "عدد الأيام القادمة", "Parameters": "المعاملات", "Print": "طباعة",
    "All reports": "جميع التقارير", "Set the report parameters to run it.": "حدّد معاملات التقرير لتشغيله.",
    "No data for these parameters.": "لا توجد بيانات لهذه المعاملات.", "As of": "كما في", "Printed": "تاريخ الطباعة",
    "Assets": "الأصول", "Opening cost": "التكلفة الافتتاحية", "Additions": "الإضافات", "Disposals": "الاستبعادات",
    "Closing cost": "التكلفة الختامية", "Dep. on additions": "إهلاك الإضافات", "Depreciation charge": "مصروف الإهلاك",
    "Dep. on disposals": "إهلاك الاستبعاد", "Accum. dep.": "مجمع الإهلاك", "NBV at disposal": "القيمة الدفترية عند الاستبعاد",
    "Gain / (loss)": "ربح / (خسارة)", "Balance": "الرصيد", "Days left": "الأيام المتبقية", "From": "من", "To": "إلى",
    "Asset ": "الأصل", "Net book value ": "صافي القيمة الدفترية",
    "Transaction date": "تاريخ الحركة", "Posted by": "بواسطة", "Count": "العدد",
    # server messages
    "A disposed asset cannot be edited": "لا يمكن تعديل أصل مستبعد", "Asset not found": "الأصل غير موجود",
    "Asset name is required": "اسم الأصل مطلوب", "Fixed asset group is required": "مجموعة الأصل مطلوبة",
    "Record not found": "السجل غير موجود", "Period not found": "الفترة غير موجودة", "The period is closed": "الفترة مغلقة",
    "Asset is disposed": "الأصل مستبعد", "Asset is already disposed": "الأصل مستبعد مسبقاً", "Invalid status": "حالة غير صالحة",
    "Invalid fiscal year": "سنة مالية غير صالحة", "The file is empty": "الملف فارغ", "File is larger than 50 MB": "الملف أكبر من 50 ميجابايت",
    "Attachment not found": "المرفق غير موجود", "Attachment file not found": "ملف المرفق غير موجود", "Unknown list": "قائمة غير معروفة",
    "Unknown report": "تقرير غير معروف", "Not found": "غير موجود",
    "This record is in use and cannot be deleted. Mark it inactive instead.": "هذا السجل مستخدم ولا يمكن حذفه. عيّنه كغير نشط بدلاً من ذلك.",
    "Code already exists or a required value is missing": "الرمز موجود مسبقاً أو توجد قيمة مطلوبة ناقصة",
    "There are no unposted depreciation lines for this period": "لا توجد سطور إهلاك غير مرحّلة لهذه الفترة",
    "This asset has depreciation or other transactions and cannot be deleted": "لهذا الأصل إهلاك أو حركات أخرى ولا يمكن حذفه",
    "Use the Transfer command to change location or cost center": "استخدم أمر التحويل لتغيير الموقع أو مركز التكلفة",
    "Nothing to transfer: choose a different location or cost center": "لا شيء للتحويل: اختر موقعاً أو مركز تكلفة مختلفاً",
    "Disposal date cannot be before the acquisition date": "تاريخ الاستبعاد لا يسبق تاريخ الاقتناء",
    "The period of the disposal date is closed": "فترة تاريخ الاستبعاد مغلقة",
    "Set the disposal clearing account in Fixed asset parameters": "حدّد حساب متحصلات الاستبعاد في معاملات الأصول الثابتة",
    "Asset group has no asset / accumulated depreciation account": "مجموعة الأصل بلا حساب أصل / مجمع إهلاك",
    "Asset group has no gain-on-disposal account": "مجموعة الأصل بلا حساب أرباح استبعاد",
    "Asset group has no loss-on-disposal account": "مجموعة الأصل بلا حساب خسائر استبعاد",
    "Residual value cannot exceed the acquisition cost": "القيمة التخريدية لا تتجاوز تكلفة الاقتناء",
    "Opening accumulated depreciation exceeds the depreciable amount": "مجمع الإهلاك الافتتاحي يتجاوز المبلغ القابل للإهلاك",
    "In-service date cannot be before the acquisition date": "تاريخ بدء الاستخدام لا يسبق تاريخ الاقتناء",
    "Fiscal year start month must be 1-12": "شهر بداية السنة المالية بين 1 و12", "Asset code prefix is required": "بادئة رقم الأصل مطلوبة",
    "From date is after To date": "تاريخ البداية بعد تاريخ النهاية", "The period is closed ": "الفترة مغلقة",
    "Cannot reach the Gooya Asset server. Is it still running?": "تعذّر الاتصال بخادم Gooya Asset. هل ما زال يعمل؟",
}
ar = {k.strip(): v for k, v in ar.items()}
keys = json.loads((ROOT / "data" / "_keys.json").read_text(encoding="utf-8"))
missing = [k for k in keys if k not in ar and " " in k]
print(len(ar), "entries; untranslated multi-word keys:", len(missing))
print("\n".join(missing))
body = "".join(f"  {json.dumps(k, ensure_ascii=False)}: {json.dumps(v, ensure_ascii=False)},\n" for k, v in ar.items())
(ROOT / "web" / "src" / "ar.ts").write_text(
    "// Arabic translations: English UI string -> Arabic. Missing keys fall back to English.\n"
    "export const AR: Record<string, string> = {\n" + body + "};\n", encoding="utf-8")
