"""Regenerate docs/api.md from the live route table:  python tools/gen_api_doc.py"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from app import auth, server  # noqa: E402  (importing server registers the routes)
from app.api.router import ROUTES  # noqa: E402

assert server.ROUTES is ROUTES

TITLES = {"setup": "Setup, lookups and settings", "assets": "Fixed assets and attachments", "depreciation": "Depreciation and periods",
          "maintenance": "Maintenance", "contacts": "Suppliers and employees", "custody": "Custody", "backups": "Backups",
          "accounts": "Accounts, users and roles", "inquiries": "Inquiries and reports"}

groups: dict[str, list[tuple[str, str, str]]] = {}
for method, rx, fn in ROUTES:
    module = fn.__module__.split(".")[-1]
    path = (rx.pattern[1:-1].replace(r"(\d+)", "{id}").replace(r"([\w-]+)", "{id}").replace(r"(\w+)", "{name}")
            .replace("(start|complete|cancel)", "{action}"))
    probe = re.sub(r"\{[^}]*\}", "1", path)
    groups.setdefault(module, []).append((method, path, auth.required_permission(method, probe) or "any signed-in user"))

out = ["# HTTP API reference", "",
       "Generated by `tools/gen_api_doc.py` from the route table (`app/api/routes/*`) and `auth.required_permission`. Bodies are JSON unless noted. "
       "State-changing calls need the `X-Requested-With: GooyaAsset` header and a valid session cookie. "
       "Errors are `{\"error\": \"message\"}` with an HTTP status (400 validation, 401 not signed in, 403 no permission, 404, 409 conflict, 500 generic).", "",
       "A request to any `/api/...` path that is not listed needs the `users.manage` permission (default deny). "
       "`PUT /api/settings` is open to any signed-in user at the router level; the handler then requires `backup.manage` for backup keys "
       "and `settings.manage` for the rest.", ""]
for module, title in TITLES.items():
    out += [f"## {title}", "", f"Module: `app/api/routes/{module}.py`", "", "| Method | Path | Permission |", "|---|---|---|"]
    out += [f"| {m} | `{p}` | {perm} |" for m, p, perm in groups[module]]
    out.append("")
(ROOT / "docs" / "api.md").write_text("\n".join(out), encoding="utf-8", newline="\n")
print({k: len(v) for k, v in groups.items()})
